FROM golang:1.23-alpine

WORKDIR /app

RUN apk add --no-cache git

# Install air for hot reload (v1.52.3 is compatible with Go 1.23)
RUN go install github.com/air-verse/air@v1.52.3

COPY go.mod go.sum ./
RUN go mod download

COPY . .

CMD ["air", "-c", ".air.toml"]
